import { describe, it, expect } from 'vitest';
import { cn, generateEAN13, generateInternalBarcode, isValidEAN13, generateSaleId, getStockStatus } from '@/lib/utils';

// ─── cn (class merger) ────────────────────────────────────────────────────────
describe('cn', () => {
  it('merges simple class names', () => {
    expect(cn('foo', 'bar')).toBe('foo bar');
  });

  it('ignores falsy values', () => {
    const includeBar: boolean = false;
    expect(cn('foo', includeBar && 'bar', undefined, null, '')).toBe('foo');
  });

  it('resolves Tailwind conflicts (last wins)', () => {
    expect(cn('p-2', 'p-4')).toBe('p-4');
  });

  it('handles conditional object syntax', () => {
    expect(cn({ 'text-red-500': true, 'text-blue-500': false })).toBe('text-red-500');
  });
});

// ─── generateInternalBarcode ──────────────────────────────────────────────────
describe('generateInternalBarcode', () => {
  it('returns a 13-character string', () => {
    expect(generateInternalBarcode()).toHaveLength(13);
  });

  it('starts with "2" (GS1 in-store internal prefix)', () => {
    for (let i = 0; i < 20; i++) {
      expect(generateInternalBarcode().startsWith('2')).toBe(true);
    }
  });

  it('contains only digits', () => {
    expect(/^\d{13}$/.test(generateInternalBarcode())).toBe(true);
  });

  it('has a valid EAN-13 check digit', () => {
    for (let i = 0; i < 10; i++) {
      const code = generateInternalBarcode();
      let sum = 0;
      for (let j = 0; j < 12; j++) {
        sum += parseInt(code[j]) * (j % 2 === 0 ? 1 : 3);
      }
      expect(parseInt(code[12])).toBe((10 - (sum % 10)) % 10);
    }
  });

  it('generates different codes each call', () => {
    const codes = new Set(Array.from({ length: 20 }, generateInternalBarcode));
    expect(codes.size).toBeGreaterThan(1);
  });

  it('generateEAN13 alias is identical to generateInternalBarcode', () => {
    expect(generateEAN13).toBe(generateInternalBarcode);
  });
});

// ─── isValidEAN13 ─────────────────────────────────────────────────────────────
describe('isValidEAN13', () => {
  it('accepts a real EAN-13 (well-known test vector)', () => {
    // 4006381333931 — Stabilo Boss highlighter, checksum verified
    expect(isValidEAN13('4006381333931')).toBe(true);
  });

  it('accepts codes generated by generateInternalBarcode', () => {
    for (let i = 0; i < 20; i++) {
      expect(isValidEAN13(generateInternalBarcode())).toBe(true);
    }
  });

  it('rejects a code with a wrong check digit', () => {
    expect(isValidEAN13('4006381333930')).toBe(false);
    expect(isValidEAN13('4006381333932')).toBe(false);
  });

  it('rejects codes shorter or longer than 13 digits', () => {
    expect(isValidEAN13('123456789012')).toBe(false);   // 12 digits
    expect(isValidEAN13('12345678901234')).toBe(false); // 14 digits
    expect(isValidEAN13('')).toBe(false);
  });

  it('rejects non-digit characters', () => {
    expect(isValidEAN13('400638133393X')).toBe(false);
    expect(isValidEAN13('400638133393 ')).toBe(false);
  });
});

// ─── generateSaleId ───────────────────────────────────────────────────────────
describe('generateSaleId', () => {
  const currentYear = new Date().getFullYear();

  it('starts with LGW-{year}-', () => {
    expect(generateSaleId(1).startsWith(`LGW-${currentYear}-`)).toBe(true);
  });

  it('zero-pads the count to 5 digits', () => {
    expect(generateSaleId(1)).toBe(`LGW-${currentYear}-00001`);
    expect(generateSaleId(42)).toBe(`LGW-${currentYear}-00042`);
    expect(generateSaleId(99999)).toBe(`LGW-${currentYear}-99999`);
  });
});

// ─── getStockStatus ───────────────────────────────────────────────────────────
describe('getStockStatus', () => {
  it('returns "stockout" when stock is 0', () => {
    expect(getStockStatus(0, 10)).toBe('stockout');
  });

  it('returns "stockout" when stock is negative', () => {
    expect(getStockStatus(-5, 10)).toBe('stockout');
  });

  it('returns "low" when stock is at the threshold', () => {
    expect(getStockStatus(10, 10)).toBe('low');
  });

  it('returns "low" when stock is below the threshold', () => {
    expect(getStockStatus(3, 10)).toBe('low');
  });

  it('returns "healthy" when stock is above the threshold', () => {
    expect(getStockStatus(11, 10)).toBe('healthy');
    expect(getStockStatus(100, 10)).toBe('healthy');
  });

  it('handles threshold of 0', () => {
    expect(getStockStatus(1, 0)).toBe('healthy');
    expect(getStockStatus(0, 0)).toBe('stockout');
  });
});
